---
output:
  pdf_document: default
  html_document: default
---
### Preparation

Run this cell to clear the variables in your global R environment.

```{r}
rm(list = ls())
ls()
```

## Libraries

```{r}
library(caret)
library(RWeka)
library(dplyr)
```


## Data files
```{r}
slack.lab.1.noVPN = read.csv("t2/slack/none/lab/slackPcapFixGapLab1_flows.csv")
slack.lab.1.1111 = read.csv("t2/slack/1.1.1.1/lab/slackPcapFixGapLab1_1111_flows.csv")
slack.lab.1.noVPN
slack.lab.1.1111

# Drop Src.ipaddr && Dest.ipaddr && start,end time && mac
drops <- c("srcIP",  "dstIP","srcMac", "dstMac", "timeFirst", "timeLast",
          "srcIPCC", "dstIPCC", "srcIPOrg", "dstIPOrg", "srcMac_dstMac_numP", "dstPortClass", "srcMacLbl_dstMacLbl", "ethVlanID",
          "hdrDesc",
          "vlanID",
          "icmpBFTypH_TypL_Code")

#"srcIPOrg", "dstIPOrg", 
slack.lab.1.noVPN <- slack.lab.1.noVPN[, !(names(slack.lab.1.noVPN) %in% drops)]
slack.lab.1.1111 <- slack.lab.1.1111[, !(names(slack.lab.1.1111) %in% drops)]
print("NA cols in slack.lab.1.noVPN:")
sum(is.na(slack.lab.1.noVPN))
print("NA cols in slack.lab.1.1111:")
sum(is.na(slack.lab.1.1111))

# Add a new column, isVPN, set to 0 for no_vpn, 1 for 1111
slack.lab.1.noVPN$isVPN <- 0
slack.lab.1.1111$isVPN <- 1

# Show summary

slack.lab.1.noVPN = data.frame(slack.lab.1.noVPN)
slack.lab.1.1111 = data.frame(slack.lab.1.1111)
```

## Prepare Data

```{r}
# Find length of the no_vpn table
slack.lab.1.nNoVPN = length(slack.lab.1.noVPN$flowInd)
slack.lab.1.nNoVPN

# Find length of the vpn table
slack.lab.1.nVPN = length(slack.lab.1.1111$flowInd)
slack.lab.1.nVPN

if (slack.lab.1.nNoVPN > slack.lab.1.nVPN) {
  slack.lab.1.nTrain = slack.lab.1.nVPN*0.7
} else {
  slack.lab.1.nTrain = slack.lab.1.nNoVPN*0.7
}

# Define Training set & Testing set
slack.lab.1.prop = slack.lab.1.nTrain/(nrow(slack.lab.1.noVPN))
set.seed(123)
slack.lab.1.noVPN.trnRows  <- sample(nrow(slack.lab.1.noVPN),nrow(slack.lab.1.noVPN)*slack.lab.1.prop)
slack.lab.1.noVPN.dtrain <- slack.lab.1.noVPN[ slack.lab.1.noVPN.trnRows,]
slack.lab.1.noVPN.dtest  <- slack.lab.1.noVPN[-slack.lab.1.noVPN.trnRows,]

slack.lab.1.1111.trnRows  <- sample(nrow(slack.lab.1.1111),nrow(slack.lab.1.1111)*0.7)
slack.lab.1.1111.dtrain <- slack.lab.1.1111[ slack.lab.1.1111.trnRows,]
slack.lab.1.1111.dtest  <- slack.lab.1.1111[-slack.lab.1.1111.trnRows,]

slack.lab.1.dtrain <- rbind(slack.lab.1.noVPN.dtrain,slack.lab.1.1111.dtrain)
slack.lab.1.dtest <- rbind(slack.lab.1.1111.dtest,slack.lab.1.noVPN.dtest)

# Remove all columns with only 1 unique value
s <- slack.lab.1.dtrain %>% select(where(~ n_distinct(.) <= 1))
drops <- c(drops,colnames(s))
length(drops)
slack.lab.1.dtrain <- slack.lab.1.dtrain %>% select(where(~ n_distinct(.) > 1))
slack.lab.1.dtrain$isVPN <- as.factor(slack.lab.1.dtrain$isVPN)

slack.lab.1.dtest <- slack.lab.1.dtest %>% select(where(~ n_distinct(.) > 1))
slack.lab.1.dtest$isVPN <- as.factor(slack.lab.1.dtest$isVPN)

nrow(slack.lab.1.dtest)
nrow(slack.lab.1.dtrain)
ncol(slack.lab.1.dtrain)
```


## Train Model

```{r}

train_control<- trainControl(method="cv", number=10)
slack.lab.1.C45Model <- train(isVPN ~., method="J48", data=slack.lab.1.dtrain,
                tuneLength = 5,
                trControl = train_control)

```



## Validation
```{r}
slack.lab.1.C45Model
slack.lab.1.C45Model$finalModel


predictions = predict(slack.lab.1.C45Model, newdata = slack.lab.1.dtest)
confusionMatrix(predictions, slack.lab.1.dtest$isVPN)
```


## Load more files
```{r}
# Remain data in lab
slack.lab.10.noVPN = read.csv("t2/slack/none/lab/slackPcapFixGapLab10re_flows.csv")
slack.lab.10.1111 = read.csv("t2/slack/1.1.1.1/lab/slackPcapFixGapLab10_1111_flows.csv")
slack.lab.3.noVPN = read.csv("t2/slack/none/lab/slackPcapFixGapLab3_flows.csv")
slack.lab.3.1111 = read.csv("t2/slack/1.1.1.1/lab/slackPcapFixGapLab3_1111_flows.csv")
slack.lab.6.noVPN = read.csv("t2/slack/none/lab/slackPcapFixGapLab6_flows.csv")
slack.lab.6.1111 = read.csv("t2/slack/1.1.1.1/lab/slackPcapFixGapLab6_1111_flows.csv")
slack.lab.8.noVPN = read.csv("t2/slack/none/lab/slackPcapFixGapLab8_flows.csv")
slack.lab.8.1111 = read.csv("t2/slack/1.1.1.1/lab/slackPcapFixGapLab8_1111_flows.csv")


# Data in residence
slack.res.10.noVPN = read.csv("t2/slack/none/res/slackPcapFixGapRes11_flows.csv")
slack.res.10.1111 = read.csv("t2/slack/1.1.1.1/res/slackPcapFixGapRes10_1111_flows.csv")
slack.res.1.noVPN = read.csv("t2/slack/none/res/slackPcapFixGapRes1_flows.csv")
slack.res.1.1111 = read.csv("t2/slack/1.1.1.1/res/slackPcapFixGapRes1_1111_flows.csv")
slack.res.3.noVPN = read.csv("t2/slack/none/res/slackPcapFixGapRes3_flows.csv")
slack.res.3.1111 = read.csv("t2/slack/1.1.1.1/res/slackPcapFixGapRes3_1111_flows.csv")
slack.res.6.noVPN = read.csv("t2/slack/none/res/slackPcapFixGapRes6_flows.csv")
slack.res.6.1111 = read.csv("t2/slack/1.1.1.1/res/slackPcapFixGapRes6_1111_flows.csv")
slack.res.8.noVPN = read.csv("t2/slack/none/res/slackPcapFixGapRes8_flows.csv")
slack.res.8.1111 = read.csv("t2/slack/1.1.1.1/res/slackPcapFixGapRes8_1111_flows.csv")

# Drop fields in drop table
# Data in lab
slack.lab.10.noVPN <- slack.lab.10.noVPN[, !(names(slack.lab.10.noVPN) %in% drops)]
slack.lab.10.1111 <- slack.lab.10.1111[, !(names(slack.lab.10.1111) %in% drops)]
slack.lab.1.noVPN <- slack.lab.1.noVPN[, !(names(slack.lab.1.noVPN) %in% drops)]
slack.lab.1.1111 <- slack.lab.1.1111[, !(names(slack.lab.1.1111) %in% drops)]
slack.lab.3.noVPN <- slack.lab.3.noVPN[, !(names(slack.lab.3.noVPN) %in% drops)]
slack.lab.3.1111 <- slack.lab.3.1111[, !(names(slack.lab.3.1111) %in% drops)]
slack.lab.6.noVPN <- slack.lab.6.noVPN[, !(names(slack.lab.6.noVPN) %in% drops)]
slack.lab.6.1111 <- slack.lab.6.1111[, !(names(slack.lab.6.1111) %in% drops)]
slack.lab.8.noVPN <- slack.lab.8.noVPN[, !(names(slack.lab.8.noVPN) %in% drops)]
slack.lab.8.1111 <- slack.lab.8.1111[, !(names(slack.lab.8.1111) %in% drops)]

# Data in residence
slack.res.10.noVPN <- slack.res.10.noVPN[, !(names(slack.res.10.noVPN) %in% drops)]
slack.res.10.1111 <- slack.res.10.1111[, !(names(slack.res.10.1111) %in% drops)]
slack.res.1.noVPN <- slack.res.1.noVPN[, !(names(slack.res.1.noVPN) %in% drops)]
slack.res.1.1111 <- slack.res.1.1111[, !(names(slack.res.1.1111) %in% drops)]
slack.res.3.noVPN <- slack.res.3.noVPN[, !(names(slack.res.3.noVPN) %in% drops)]
slack.res.3.1111 <- slack.res.3.1111[, !(names(slack.res.3.1111) %in% drops)]
slack.res.6.noVPN <- slack.res.6.noVPN[, !(names(slack.res.6.noVPN) %in% drops)]
slack.res.6.1111 <- slack.res.6.1111[, !(names(slack.res.6.1111) %in% drops)]
slack.res.8.noVPN <- slack.res.8.noVPN[, !(names(slack.res.8.noVPN) %in% drops)]
slack.res.8.1111 <- slack.res.8.1111[, !(names(slack.res.8.1111) %in% drops)]


# Add a new column, isVPN, set to 0 for no_vpn, 1 for 1111
# Data in lab
slack.lab.10.noVPN$isVPN <- 0
slack.lab.10.1111$isVPN <- 1
slack.lab.3.noVPN$isVPN <- 0
slack.lab.3.1111$isVPN <- 1
slack.lab.6.noVPN$isVPN <- 0
slack.lab.6.1111$isVPN <- 1
slack.lab.8.noVPN$isVPN <- 0
slack.lab.8.1111$isVPN <- 1

# Data in residence
slack.res.10.noVPN$isVPN <- 0
slack.res.10.1111$isVPN <- 1
slack.res.1.noVPN$isVPN <- 0
slack.res.1.1111$isVPN <- 1
slack.res.3.noVPN$isVPN <- 0
slack.res.3.1111$isVPN <- 1
slack.res.6.noVPN$isVPN <- 0
slack.res.6.1111$isVPN <- 1
slack.res.8.noVPN$isVPN <- 0
slack.res.8.1111$isVPN <- 1

# Show summary
slack.lab.10.noVPN = data.frame(slack.lab.10.noVPN)
slack.lab.10.1111 = data.frame(slack.lab.10.1111)
slack.lab.3.noVPN = data.frame(slack.lab.3.noVPN)
slack.lab.3.1111 = data.frame(slack.lab.3.1111)
slack.lab.6.noVPN = data.frame(slack.lab.6.noVPN)
slack.lab.6.1111 = data.frame(slack.lab.6.1111)
slack.lab.8.noVPN = data.frame(slack.lab.8.noVPN)
slack.lab.8.1111 = data.frame(slack.lab.8.1111)

slack.res.10.noVPN = data.frame(slack.res.10.noVPN)
slack.res.10.1111 = data.frame(slack.res.10.1111)
slack.res.1.noVPN = data.frame(slack.res.1.noVPN)
slack.res.1.1111 = data.frame(slack.res.1.1111)
slack.res.3.noVPN = data.frame(slack.res.3.noVPN)
slack.res.3.1111 = data.frame(slack.res.3.1111)
slack.res.6.noVPN = data.frame(slack.res.6.noVPN)
slack.res.6.1111 = data.frame(slack.res.6.1111)
slack.res.8.noVPN = data.frame(slack.res.8.noVPN)
slack.res.8.1111 = data.frame(slack.res.8.1111)

slack.lab.10.data <- rbind(slack.lab.10.1111,slack.lab.10.noVPN)
slack.lab.3.data <- rbind(slack.lab.3.1111,slack.lab.3.noVPN)
slack.lab.6.data <- rbind(slack.lab.6.1111,slack.lab.6.noVPN)
slack.lab.8.data <- rbind(slack.lab.8.1111,slack.lab.8.noVPN)


slack.res.3.data <- rbind(slack.res.3.1111,slack.res.3.noVPN)

print("Number of rows in slack.lab.3.data:")
nrow(slack.lab.3.data)
print("Number of cols in slack.lab.3.data:")
ncol(slack.lab.3.data)

```

## Predicate
```{r}
predictions.lab.10 = predict(slack.lab.1.C45Model, newdata = slack.lab.10.data)
confMatrixes.lab.10 <- confusionMatrix(predictions.lab.10, as.factor(slack.lab.10.data$isVPN))

predictions.lab.3 = predict(slack.lab.1.C45Model, newdata = slack.lab.3.data)
confMatrixes.lab.3 <- confusionMatrix(predictions.lab.3, as.factor(slack.lab.3.data$isVPN))

predictions.lab.6 = predict(slack.lab.1.C45Model, newdata = slack.lab.6.data)
confMatrixes.lab.6 <- confusionMatrix(predictions.lab.6, as.factor(slack.lab.6.data$isVPN))

predictions.lab.8 = predict(slack.lab.1.C45Model, newdata = slack.lab.8.data)
confMatrixes.lab.8 <- confusionMatrix(predictions.lab.8, as.factor(slack.lab.8.data$isVPN))

predictions.res.3 = predict(slack.lab.1.C45Model, newdata = slack.res.3.data)
confMatrixes.res.3 <- confusionMatrix(predictions.res.3, as.factor(slack.res.3.data$isVPN))

confMatrixes.lab.10$overall
confMatrixes.lab.3$overall
confMatrixes.lab.6$overall
confMatrixes.lab.8$overall
confMatrixes.res.3$overall
```


## Data process function
```{r}
process_slack_data <- function(data) {
  data.noVPN <- get(paste(data, "noVPN", sep = "."))
  data.1111 <- get(paste(data, "1111", sep = "."))
  
  data.prop = nrow(data.1111)*0.7 / nrow(data.noVPN)
  
  data.noVPN.trnRows  <- sample(nrow(data.noVPN),nrow(data.noVPN)*data.prop)
  data.noVPN.dtrain <- data.noVPN[ data.noVPN.trnRows,]
  data.noVPN.dtest  <- data.noVPN[-data.noVPN.trnRows,]

  data.1111.trnRows <- sample(nrow(data.1111),nrow(data.1111)*0.7)
  data.1111.dtrain <- data.1111[ data.1111.trnRows,]
  data.1111.dtest  <- data.1111[-data.1111.trnRows,]

  data.dtrain <- rbind(data.noVPN.dtrain,data.1111.dtrain)
  data.dtest <- rbind(data.noVPN.dtest,data.1111.dtest)

  data.dtrain$isVPN <- as.factor(data.dtrain$isVPN)
  data.dtest$isVPN <- as.factor(data.dtest$isVPN)
  
  assign(paste(data, "dtest", sep = "."), data.dtest, envir = globalenv())
  assign(paste(data, "dtrain", sep = "."), data.dtrain, envir = globalenv())
}

```


# Train model with more data
```{r}
slack.lab.noVPN <- rbind(slack.lab.10.noVPN,slack.lab.1.noVPN,slack.lab.3.noVPN,
                        slack.lab.6.noVPN,slack.lab.8.noVPN)
slack.lab.1111 <- rbind(slack.lab.10.1111,slack.lab.1.1111,slack.lab.3.1111,
                        slack.lab.6.1111,slack.lab.8.1111)

slack.res.noVPN <- rbind(slack.res.10.noVPN,slack.res.1.noVPN,slack.res.3.noVPN,
                         slack.res.6.noVPN,slack.res.8.noVPN)
slack.res.1111 <- rbind(slack.res.10.1111,slack.res.1.1111,slack.res.3.1111,
                        slack.res.6.1111,slack.res.8.1111)
slack.res.data <- rbind(slack.res.noVPN, slack.res.1111)
slack.res.data$isVPN <- as.factor(slack.res.data$isVPN)

nrow(slack.lab.noVPN)
nrow(slack.lab.1111)

process_slack_data("slack.lab")
slack.lab.dtrain

process_slack_data("slack.res")
slack.res.dtrain

slack.res.dtrain <- slack.res.dtrain %>% select(where(~ n_distinct(.) > 1))
slack.res.dtest <- slack.res.dtest %>% select(where(~ n_distinct(.) > 1))

slack.noVPN <- rbind(slack.lab.noVPN, slack.res.noVPN)
slack.1111 <- rbind(slack.lab.1111, slack.res.1111)
process_slack_data("slack")

```


```{r}
train_control<- trainControl(method="cv", number=10)
slack.lab.C45Model <- train(isVPN ~., method="J48", data=slack.lab.dtrain,
                tuneLength = 5,
                trControl = train_control)

slack.res.C45Model <- train(isVPN ~., method="J48", data=slack.res.dtrain,
                tuneLength = 5,
                trControl = train_control)

slack.C45Model <- train(isVPN ~., method="J48", data=slack.dtrain,
                tuneLength = 5,
                trControl = train_control)

```

```{r}
slack.lab.C45Model
slack.lab.C45Model$finalModel

predictions.lab.lab = predict(slack.lab.C45Model, newdata = slack.lab.dtest)
confMatrixes.lab.lab <- confusionMatrix(predictions.lab, slack.lab.dtest$isVPN)

predictions.lab.res = predict(slack.lab.C45Model, newdata = slack.res.data)
confMatrixes.lab.res <- confusionMatrix(predictions.res, slack.res.data$isVPN)

confMatrixes.lab.lab$overall
confMatrixes.lab.res$overall
```

```{r}
slack.res.C45Model
slack.res.C45Model$finalModel

predictions.res.lab = predict(slack.res.C45Model, newdata = slack.lab.dtest)
confMatrixes.res.lab <- confusionMatrix(predictions.res.lab, slack.lab.dtest$isVPN)

predictions.res.res = predict(slack.res.C45Model, newdata = slack.res.dtest)
confMatrixes.res.res <- confusionMatrix(predictions.res.res, slack.res.dtest$isVPN)

confMatrixes.res.lab$overall
confMatrixes.res.res$overall

```

```{r}
slack.C45Model
slack.C45Model$finalModel

predictions.lab = predict(slack.C45Model, newdata = slack.dtest)
confMatrixes.lab <- confusionMatrix(predictions.lab, slack.dtest$isVPN)

confMatrixes.lab$overall
```