---
output:
  pdf_document: default
  html_document: default
---

### Preparation

Run this cell to clear the variables in your global R environment.

```{r}
rm(list = ls())
ls()
```

## Libraries

```{r}
library(caret)
library(RWeka)
library(dplyr)
```


## Define basics
```{r}
# Drop Src.ipaddr && Dest.ipaddr && start,end time && mac
drops <- c("srcIP",  "dstIP","srcMac", "dstMac", "timeFirst", "timeLast",
          "srcIPCC", "dstIPCC", "srcIPOrg", "dstIPOrg", "srcMac_dstMac_numP", "dstPortClass", "srcMacLbl_dstMacLbl", "ethVlanID",
          "hdrDesc",
          "vlanID",
          "icmpBFTypH_TypL_Code")

```


## Data file process function
```{r}
load_data <- function(data) {
  data.noVPN <- get(paste(data, "noVPN", sep = "."))
  data.1111 <- get(paste(data, "1111", sep = "."))
  
  data.noVPN <- data.noVPN[, !(names(data.noVPN) %in% drops)]
  data.1111 <- data.1111[, !(names(data.1111) %in% drops)]
  
  data.noVPN$isVPN <- 0
  data.1111$isVPN <- 1
  
  data.noVPN = data.frame(data.noVPN)
  data.1111 = data.frame(data.1111)
  data.data <- rbind(data.1111,data.noVPN)
  
  assign(paste(data, "noVPN", sep = "."), data.noVPN, envir = globalenv())
  assign(paste(data, "1111", sep = "."), data.1111, envir = globalenv())
  assign(paste(data, "data", sep = "."), data.data, envir = globalenv())
}
```


## Load data files
```{r}
twitch.lab.10.noVPN = read.csv("t2/streaming/none/lab/streamingCapLab10_flows.csv")
twitch.lab.1.noVPN = read.csv("t2/streaming/none/lab/streamingCapLab1_flows.csv")
twitch.lab.3.noVPN = read.csv("t2/streaming/none/lab/streamingCapLab3_flows.csv")
twitch.lab.6.noVPN = read.csv("t2/streaming/none/lab/streamingCapLab6_flows.csv")
twitch.lab.8.noVPN = read.csv("t2/streaming/none/lab/streamingCapLab8_flows.csv")

twitch.lab.10.1111 = read.csv("t2/streaming/1.1.1.1/lab/streamingCapLab10_1111_flows.csv")
twitch.lab.1.1111 = read.csv("t2/streaming/1.1.1.1/lab/streamingCapLab1_1111_flows.csv")
twitch.lab.3.1111 = read.csv("t2/streaming/1.1.1.1/lab/streamingCapLab3_1111_flows.csv")
twitch.lab.6.1111 = read.csv("t2/streaming/1.1.1.1/lab/streamingCapLab6_1111_flows.csv")
twitch.lab.8.1111 = read.csv("t2/streaming/1.1.1.1/lab/streamingCapLab8_1111_flows.csv")

twitch.res.10.noVPN = read.csv("t2/streaming/none/res/streamingCapRes10_flows.csv")
twitch.res.1.noVPN = read.csv("t2/streaming/none/res/streamingCapRes1_flows.csv")
twitch.res.3.noVPN = read.csv("t2/streaming/none/res/streamingCapRes3_flows.csv")
twitch.res.6.noVPN = read.csv("t2/streaming/none/res/streamingCapRes6_flows.csv")
twitch.res.8.noVPN = read.csv("t2/streaming/none/res/streamingCapRes8_flows.csv")

load_data("twitch.lab.10")
load_data("twitch.lab.1")
load_data("twitch.lab.3")
load_data("twitch.lab.6")
load_data("twitch.lab.8")

twitch.lab.noVPN <- rbind(twitch.lab.10.noVPN,twitch.lab.1.noVPN,twitch.lab.3.noVPN,
                        twitch.lab.6.noVPN,twitch.lab.8.noVPN)
twitch.lab.1111 <- rbind(twitch.lab.10.1111,twitch.lab.1.1111,twitch.lab.3.1111,
                        twitch.lab.6.1111,twitch.lab.8.1111)
twitch.lab.data <- rbind(twitch.lab.noVPN,twitch.lab.1111)

```


## Clean data
```{r}


```


## Models - C45
```{}


```


## Validation - C45
```{r}

```


## Models - Random Forest
```{r}

```


## Validation - Random Forest
```{r}

```

## Models - LASSO
```{r}


```

## Validation - LASSO
```{r}

```